sudo: required
language: node_js
install: npm install
script: npm test
node_js:
  - node
  - 10
addons:
  code_climate:
    repo_token: 9840b8b56f6d10209b3478d41f7ba5102d02981435df129bb18554a529359c62
before_install:
  - 'apt-get install libgconf-2-4'
before_script:
  - 'npm install -g codeclimate-test-reporter'
after_script:
  - 'codeclimate-test-reporter < coverage/lcov.info'
notifications:
  email: false
  slack:
    rooms:
      secure: Y7GyAUEjnjzyazj3zo3PXcl9Z1TN7SGjfUGQacJ+U/pCKfZKzgUhezZ5hTMz71bxL6/+2TuvKHQM3NQgrgR5JhdsPlrJfIW9FK2rNNPBN9p/DWZGv2bjEKPCcstdkuF/1NCru8up9092pZ3Fa8n6bjXicswCMVKjAmYrXqsWEMU=
