language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: your repo token
notifications:
  slack:
    rooms:
      secure: fXcSgznsrcIldoOTGwQtDfbu2Kkd/VuKLCvxReTj4qUTKTDtZqOevAt6rO5ZKzGOKu41JLiqctovHuks1q3okK7L18wmhs9y1EbfXyQJS1ELioIv66jkqtjlWNNIUn3Uc6jzR/RqE4QkJIh0MKr5/aWtLx4EUyEE7C3QYzDfJgdpKAONX1Bm1gLgrsqb+6Rb/n4WhRcFh/RAfznDsTSxu6buE6TjOu09cuz2164i1g1x9vnToC3WkF0gL7JORPnhJTb39bpHq9Lj46gVv4CWuJu1WP7qjn9uU/ct6w3co038+xgZDFAyMWiaopKbRtoJrEt4+JaHu4POWEjf7/BqNq+4OeCC44cz5/s/HkeiskgICdL4Bv5lLjmxVRaEAkAgcTNNp9ABwDCMa0VG5DOs0hdxjdgLICfGNQxBOh9RI9o7XHgcHN7N7ree3V46R4iiqwv12UVnkd8W+3PRRaF6dYK6qC4PC0PV6ln9k8uJ/2Yfi/0SyEf90AtNt8uG8JkFS854h5QyxtAtOFdvM3u/mGeCdyh7cferRkzyELaUymMqjpAsMIBkVFC+XvpcDEcFJykFqiuA+K5sUcVHiLFanssTCk6gtwV+s0y4BCIrhKSz17lPx8E2HAt2m3sHDL7ohH6AlLfAIOZakkbWyj6feBksgi+SzIk5Lzc4aGZFSmk=
  email: false
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
